site_name: Chronos Context Timer Documentation
site_url: https://adambirds.github.io/chronos/
repo_url: https://github.com/adambirds/chronos
repo_name: adambirds/chronos
copyright: "Copyright &copy; 2024 Adam Birds"
theme:
  name: material
  custom_dir: overrides
  palette:
    scheme: slate
    primary: red
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
    - navigation.top
extra:
  version:
    provider: mike
    default: latest
plugins:
  - search:
      lang: en
  - social:
      cards: true
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences